site_name: My Docs
theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'amber'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'cloud'
  feature:
    tabs: true
  favicon: 'images/favicon.png'
nav:
  - Home: index.md
  - About: about.md
  - Code: code.md
  - Image: image.md
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
